/* pua_map.h  —  auto-generated by engine/fonts/gen-pua-header.py
 * DO NOT EDIT MANUALLY. Edit engine/fonts/pua-mapping.json, then regenerate.
 *
 * Maps PK font char codes (0-255) to Unicode codepoints for the tabbo lute fonts.
 * ASCII-range glyphs (letters, punctuation defined via MF char literals) stay
 * at their natural codepoints. All numeric PK codes map to PUA (U+E000 + pk_code).
 *
 * Usage in Phase 1 json_print:
 *   #include "pua_map.h"
 *   int unicode = pk_to_pua(pk_char_code);  // -1 if unmapped
 */

#ifndef PUA_MAP_H
#define PUA_MAP_H

/* Number of mapped entries. */
#define PUA_MAP_ENTRIES 216

/* Lookup table: { pk_code, unicode_codepoint }. Sorted by pk_code. */
static const struct { int pk; int unicode; } pua_map_table[] = {
    {  0, 0xE000},  /* PK   0 -> U+E000 */
    {  1, 0xE001},  /* PK   1 -> U+E001 */
    {  2, 0xE002},  /* PK   2 -> U+E002 */
    {  3, 0xE003},  /* PK   3 -> U+E003 */
    {  4, 0xE004},  /* PK   4 -> U+E004 */
    {  5, 0xE005},  /* PK   5 -> U+E005 */
    {  6, 0xE006},  /* PK   6 -> U+E006 */
    {  7, 0xE007},  /* PK   7 -> U+E007 */
    {  8, 0xE008},  /* PK   8 -> U+E008 */
    {  9, 0xE009},  /* PK   9 -> U+E009 */
    { 10, 0xE00A},  /* PK  10 -> U+E00A */
    { 11, 0xE00B},  /* PK  11 -> U+E00B */
    { 12, 0xE00C},  /* PK  12 -> U+E00C */
    { 13, 0xE00D},  /* PK  13 -> U+E00D */
    { 14, 0xE00E},  /* PK  14 -> U+E00E */
    { 15, 0xE00F},  /* PK  15 -> U+E00F */
    { 16, 0xE010},  /* PK  16 -> U+E010 */
    { 17, 0xE011},  /* PK  17 -> U+E011 */
    { 18, 0xE012},  /* PK  18 -> U+E012 */
    { 19, 0xE013},  /* PK  19 -> U+E013 */
    { 20, 0xE014},  /* PK  20 -> U+E014 */
    { 21, 0xE015},  /* PK  21 -> U+E015 */
    { 22, 0xE016},  /* PK  22 -> U+E016 */
    { 23, 0xE017},  /* PK  23 -> U+E017 */
    { 24, 0xE018},  /* PK  24 -> U+E018 */
    { 25, 0xE019},  /* PK  25 -> U+E019 */
    { 26, 0xE01A},  /* PK  26 -> U+E01A */
    { 27, 0xE01B},  /* PK  27 -> U+E01B */
    { 34, 0x0022},  /* PK  34 -> U+0022 */
    { 35, 0x0023},  /* PK  35 -> U+0023 */
    { 36, 0x0024},  /* PK  36 -> U+0024 */
    { 39, 0x0027},  /* PK  39 -> U+0027 */
    { 40, 0x0028},  /* PK  40 -> U+0028 */
    { 41, 0x0029},  /* PK  41 -> U+0029 */
    { 43, 0x002B},  /* PK  43 -> U+002B */
    { 46, 0x002E},  /* PK  46 -> U+002E */
    { 47, 0x002F},  /* PK  47 -> U+002F */
    { 55, 0xE037},  /* PK  55 -> U+E037 */
    { 56, 0xE038},  /* PK  56 -> U+E038 */
    { 57, 0xE039},  /* PK  57 -> U+E039 */
    { 58, 0x003A},  /* PK  58 -> U+003A */
    { 59, 0x003B},  /* PK  59 -> U+003B */
    { 60, 0x003C},  /* PK  60 -> U+003C */
    { 61, 0x003D},  /* PK  61 -> U+003D */
    { 62, 0x003E},  /* PK  62 -> U+003E */
    { 63, 0x003F},  /* PK  63 -> U+003F */
    { 64, 0x0040},  /* PK  64 -> U+0040 */
    { 68, 0x0044},  /* PK  68 -> U+0044 */
    { 69, 0x0045},  /* PK  69 -> U+0045 */
    { 70, 0x0046},  /* PK  70 -> U+0046 */
    { 71, 0x0047},  /* PK  71 -> U+0047 */
    { 72, 0x0048},  /* PK  72 -> U+0048 */
    { 73, 0x0049},  /* PK  73 -> U+0049 */
    { 74, 0x004A},  /* PK  74 -> U+004A */
    { 76, 0x004C},  /* PK  76 -> U+004C */
    { 80, 0x0050},  /* PK  80 -> U+0050 */
    { 81, 0x0051},  /* PK  81 -> U+0051 */
    { 82, 0x0052},  /* PK  82 -> U+0052 */
    { 83, 0x0053},  /* PK  83 -> U+0053 */
    { 84, 0x0054},  /* PK  84 -> U+0054 */
    { 85, 0x0055},  /* PK  85 -> U+0055 */
    { 86, 0x0056},  /* PK  86 -> U+0056 */
    { 87, 0x0057},  /* PK  87 -> U+0057 */
    { 88, 0xE058},  /* PK  88 -> U+E058 */
    { 89, 0x0059},  /* PK  89 -> U+0059 */
    { 90, 0x005A},  /* PK  90 -> U+005A */
    { 91, 0x005B},  /* PK  91 -> U+005B */
    { 92, 0xE05C},  /* PK  92 -> U+E05C */
    { 93, 0x005D},  /* PK  93 -> U+005D */
    { 94, 0x005E},  /* PK  94 -> U+005E */
    { 95, 0x005F},  /* PK  95 -> U+005F */
    { 96, 0x0060},  /* PK  96 -> U+0060 */
    { 97, 0x0061},  /* PK  97 -> U+0061 */
    { 98, 0x0062},  /* PK  98 -> U+0062 */
    { 99, 0x0063},  /* PK  99 -> U+0063 */
    {100, 0x0064},  /* PK 100 -> U+0064 */
    {101, 0x0065},  /* PK 101 -> U+0065 */
    {102, 0x0066},  /* PK 102 -> U+0066 */
    {103, 0x0067},  /* PK 103 -> U+0067 */
    {104, 0x0068},  /* PK 104 -> U+0068 */
    {105, 0x0069},  /* PK 105 -> U+0069 */
    {106, 0x006A},  /* PK 106 -> U+006A */
    {107, 0x006B},  /* PK 107 -> U+006B */
    {108, 0x006C},  /* PK 108 -> U+006C */
    {109, 0x006D},  /* PK 109 -> U+006D */
    {110, 0x006E},  /* PK 110 -> U+006E */
    {111, 0x006F},  /* PK 111 -> U+006F */
    {112, 0x0070},  /* PK 112 -> U+0070 */
    {113, 0x0071},  /* PK 113 -> U+0071 */
    {114, 0xE072},  /* PK 114 -> U+E072 */
    {115, 0x0073},  /* PK 115 -> U+0073 */
    {116, 0x0074},  /* PK 116 -> U+0074 */
    {117, 0x0075},  /* PK 117 -> U+0075 */
    {119, 0x0077},  /* PK 119 -> U+0077 */
    {120, 0x0078},  /* PK 120 -> U+0078 */
    {121, 0x0079},  /* PK 121 -> U+0079 */
    {122, 0x007A},  /* PK 122 -> U+007A */
    {124, 0x007C},  /* PK 124 -> U+007C */
    {126, 0x007E},  /* PK 126 -> U+007E */
    {128, 0xE080},  /* PK 128 -> U+E080 */
    {129, 0xE081},  /* PK 129 -> U+E081 */
    {130, 0xE082},  /* PK 130 -> U+E082 */
    {131, 0xE083},  /* PK 131 -> U+E083 */
    {132, 0xE084},  /* PK 132 -> U+E084 */
    {133, 0xE085},  /* PK 133 -> U+E085 */
    {134, 0xE086},  /* PK 134 -> U+E086 */
    {135, 0xE087},  /* PK 135 -> U+E087 */
    {136, 0xE088},  /* PK 136 -> U+E088 */
    {137, 0xE089},  /* PK 137 -> U+E089 */
    {138, 0xE08A},  /* PK 138 -> U+E08A */
    {139, 0xE08B},  /* PK 139 -> U+E08B */
    {140, 0xE08C},  /* PK 140 -> U+E08C */
    {141, 0xE08D},  /* PK 141 -> U+E08D */
    {142, 0xE08E},  /* PK 142 -> U+E08E */
    {143, 0xE08F},  /* PK 143 -> U+E08F */
    {144, 0xE090},  /* PK 144 -> U+E090 */
    {145, 0xE091},  /* PK 145 -> U+E091 */
    {146, 0xE092},  /* PK 146 -> U+E092 */
    {147, 0xE093},  /* PK 147 -> U+E093 */
    {148, 0xE094},  /* PK 148 -> U+E094 */
    {149, 0xE095},  /* PK 149 -> U+E095 */
    {150, 0xE096},  /* PK 150 -> U+E096 */
    {151, 0xE097},  /* PK 151 -> U+E097 */
    {152, 0xE098},  /* PK 152 -> U+E098 */
    {153, 0xE099},  /* PK 153 -> U+E099 */
    {154, 0xE09A},  /* PK 154 -> U+E09A */
    {155, 0xE09B},  /* PK 155 -> U+E09B */
    {156, 0xE09C},  /* PK 156 -> U+E09C */
    {157, 0xE09D},  /* PK 157 -> U+E09D */
    {158, 0xE09E},  /* PK 158 -> U+E09E */
    {159, 0xE09F},  /* PK 159 -> U+E09F */
    {160, 0xE0A0},  /* PK 160 -> U+E0A0 */
    {161, 0xE0A1},  /* PK 161 -> U+E0A1 */
    {162, 0xE0A2},  /* PK 162 -> U+E0A2 */
    {163, 0xE0A3},  /* PK 163 -> U+E0A3 */
    {164, 0xE0A4},  /* PK 164 -> U+E0A4 */
    {165, 0xE0A5},  /* PK 165 -> U+E0A5 */
    {166, 0xE0A6},  /* PK 166 -> U+E0A6 */
    {167, 0xE0A7},  /* PK 167 -> U+E0A7 */
    {168, 0xE0A8},  /* PK 168 -> U+E0A8 */
    {169, 0xE0A9},  /* PK 169 -> U+E0A9 */
    {170, 0xE0AA},  /* PK 170 -> U+E0AA */
    {171, 0xE0AB},  /* PK 171 -> U+E0AB */
    {172, 0xE0AC},  /* PK 172 -> U+E0AC */
    {173, 0xE0AD},  /* PK 173 -> U+E0AD */
    {175, 0xE0AF},  /* PK 175 -> U+E0AF */
    {176, 0xE0B0},  /* PK 176 -> U+E0B0 */
    {177, 0xE0B1},  /* PK 177 -> U+E0B1 */
    {178, 0xE0B2},  /* PK 178 -> U+E0B2 */
    {179, 0xE0B3},  /* PK 179 -> U+E0B3 */
    {180, 0xE0B4},  /* PK 180 -> U+E0B4 */
    {181, 0xE0B5},  /* PK 181 -> U+E0B5 */
    {182, 0xE0B6},  /* PK 182 -> U+E0B6 */
    {183, 0xE0B7},  /* PK 183 -> U+E0B7 */
    {184, 0xE0B8},  /* PK 184 -> U+E0B8 */
    {185, 0xE0B9},  /* PK 185 -> U+E0B9 */
    {186, 0xE0BA},  /* PK 186 -> U+E0BA */
    {187, 0xE0BB},  /* PK 187 -> U+E0BB */
    {188, 0xE0BC},  /* PK 188 -> U+E0BC */
    {191, 0xE0BF},  /* PK 191 -> U+E0BF */
    {194, 0xE0C2},  /* PK 194 -> U+E0C2 */
    {195, 0xE0C3},  /* PK 195 -> U+E0C3 */
    {196, 0xE0C4},  /* PK 196 -> U+E0C4 */
    {197, 0xE0C5},  /* PK 197 -> U+E0C5 */
    {198, 0xE0C6},  /* PK 198 -> U+E0C6 */
    {199, 0xE0C7},  /* PK 199 -> U+E0C7 */
    {202, 0xE0CA},  /* PK 202 -> U+E0CA */
    {203, 0xE0CB},  /* PK 203 -> U+E0CB */
    {204, 0xE0CC},  /* PK 204 -> U+E0CC */
    {205, 0xE0CD},  /* PK 205 -> U+E0CD */
    {206, 0xE0CE},  /* PK 206 -> U+E0CE */
    {207, 0xE0CF},  /* PK 207 -> U+E0CF */
    {211, 0xE0D3},  /* PK 211 -> U+E0D3 */
    {212, 0xE0D4},  /* PK 212 -> U+E0D4 */
    {213, 0xE0D5},  /* PK 213 -> U+E0D5 */
    {214, 0xE0D6},  /* PK 214 -> U+E0D6 */
    {215, 0xE0D7},  /* PK 215 -> U+E0D7 */
    {216, 0xE0D8},  /* PK 216 -> U+E0D8 */
    {217, 0xE0D9},  /* PK 217 -> U+E0D9 */
    {218, 0xE0DA},  /* PK 218 -> U+E0DA */
    {219, 0xE0DB},  /* PK 219 -> U+E0DB */
    {220, 0xE0DC},  /* PK 220 -> U+E0DC */
    {221, 0xE0DD},  /* PK 221 -> U+E0DD */
    {222, 0xE0DE},  /* PK 222 -> U+E0DE */
    {223, 0xE0DF},  /* PK 223 -> U+E0DF */
    {224, 0xE0E0},  /* PK 224 -> U+E0E0 */
    {225, 0xE0E1},  /* PK 225 -> U+E0E1 */
    {226, 0xE0E2},  /* PK 226 -> U+E0E2 */
    {227, 0xE0E3},  /* PK 227 -> U+E0E3 */
    {228, 0xE0E4},  /* PK 228 -> U+E0E4 */
    {229, 0xE0E5},  /* PK 229 -> U+E0E5 */
    {231, 0xE0E7},  /* PK 231 -> U+E0E7 */
    {232, 0xE0E8},  /* PK 232 -> U+E0E8 */
    {233, 0xE0E9},  /* PK 233 -> U+E0E9 */
    {234, 0xE0EA},  /* PK 234 -> U+E0EA */
    {235, 0xE0EB},  /* PK 235 -> U+E0EB */
    {236, 0xE0EC},  /* PK 236 -> U+E0EC */
    {237, 0xE0ED},  /* PK 237 -> U+E0ED */
    {238, 0xE0EE},  /* PK 238 -> U+E0EE */
    {239, 0xE0EF},  /* PK 239 -> U+E0EF */
    {240, 0xE0F0},  /* PK 240 -> U+E0F0 */
    {241, 0xE0F1},  /* PK 241 -> U+E0F1 */
    {242, 0xE0F2},  /* PK 242 -> U+E0F2 */
    {243, 0xE0F3},  /* PK 243 -> U+E0F3 */
    {244, 0xE0F4},  /* PK 244 -> U+E0F4 */
    {245, 0xE0F5},  /* PK 245 -> U+E0F5 */
    {246, 0xE0F6},  /* PK 246 -> U+E0F6 */
    {247, 0xE0F7},  /* PK 247 -> U+E0F7 */
    {248, 0xE0F8},  /* PK 248 -> U+E0F8 */
    {249, 0xE0F9},  /* PK 249 -> U+E0F9 */
    {250, 0xE0FA},  /* PK 250 -> U+E0FA */
    {251, 0xE0FB},  /* PK 251 -> U+E0FB */
    {252, 0xE0FC},  /* PK 252 -> U+E0FC */
    {253, 0xE0FD},  /* PK 253 -> U+E0FD */
    {254, 0xE0FE},  /* PK 254 -> U+E0FE */
    {255, 0xE0FF},  /* PK 255 -> U+E0FF */
};

/*
 * pk_to_pua: convert a PK font char code to its Unicode codepoint.
 * Returns -1 if the code has no mapping (treat as unmapped/.notdef).
 * Binary search: table is sorted by pk_code. Called at JSON-emit time,
 * not in the layout hot path.
 */
static inline int pk_to_pua(int pk_code) {
    int lo = 0, hi = PUA_MAP_ENTRIES - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (pua_map_table[mid].pk == pk_code) return pua_map_table[mid].unicode;
        if (pua_map_table[mid].pk < pk_code) lo = mid + 1;
        else hi = mid - 1;
    }
    return -1;
}

#endif /* PUA_MAP_H */
