#!/usr/bin/env python3
"""
Generate engine/include/pua_map.h from engine/fonts/pua-mapping.json.

Run from the repo root:
  python3 engine/fonts/gen-pua-header.py

The generated header is checked in. Re-run this script whenever pua-mapping.json changes.
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MAPPING_PATH = os.path.join(SCRIPT_DIR, "pua-mapping.json")
HEADER_PATH = os.path.join(os.path.dirname(SCRIPT_DIR), "include", "pua_map.h")


def build_table(mapping: dict) -> list[tuple[int, int]]:
    """Return sorted list of (pk_code, unicode_codepoint) pairs."""
    entries = []
    for pk in mapping["ascii_zone"]["codes"]:
        entries.append((pk, pk))  # identity mapping for ASCII zone
    offset = mapping["pua_zone"]["offset"]
    for pk in mapping["pua_zone"]["codes"]:
        entries.append((pk, offset + pk))
    entries.sort()
    return entries


def main() -> None:
    with open(MAPPING_PATH) as f:
        mapping = json.load(f)

    table = build_table(mapping)

    lines = []
    lines.append("/* pua_map.h  —  auto-generated by engine/fonts/gen-pua-header.py")
    lines.append(" * DO NOT EDIT MANUALLY. Edit engine/fonts/pua-mapping.json, then regenerate.")
    lines.append(" *")
    lines.append(" * Maps PK font char codes (0-255) to Unicode codepoints for the tabbo lute fonts.")
    lines.append(" * ASCII-range glyphs (letters, punctuation defined via MF char literals) stay")
    lines.append(" * at their natural codepoints. All numeric PK codes map to PUA (U+E000 + pk_code).")
    lines.append(" *")
    lines.append(" * Usage in Phase 1 json_print:")
    lines.append(" *   #include \"pua_map.h\"")
    lines.append(" *   int unicode = pk_to_pua(pk_char_code);  // -1 if unmapped")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef PUA_MAP_H")
    lines.append("#define PUA_MAP_H")
    lines.append("")
    lines.append("/* Number of mapped entries. */")
    lines.append(f"#define PUA_MAP_ENTRIES {len(table)}")
    lines.append("")
    lines.append("/* Lookup table: { pk_code, unicode_codepoint }. Sorted by pk_code. */")
    lines.append("static const struct { int pk; int unicode; } pua_map_table[] = {")

    for pk, uni in table:
        comment = f"  /* PK {pk:3d} -> U+{uni:04X} */"
        lines.append(f"    {{{pk:3d}, 0x{uni:04X}}},{comment}")

    lines.append("};")
    lines.append("")
    lines.append("/*")
    lines.append(" * pk_to_pua: convert a PK font char code to its Unicode codepoint.")
    lines.append(" * Returns -1 if the code has no mapping (treat as unmapped/.notdef).")
    lines.append(" * Binary search: table is sorted by pk_code. Called at JSON-emit time,")
    lines.append(" * not in the layout hot path.")
    lines.append(" */")
    lines.append("static inline int pk_to_pua(int pk_code) {")
    lines.append("    int lo = 0, hi = PUA_MAP_ENTRIES - 1;")
    lines.append("    while (lo <= hi) {")
    lines.append("        int mid = (lo + hi) / 2;")
    lines.append("        if (pua_map_table[mid].pk == pk_code) return pua_map_table[mid].unicode;")
    lines.append("        if (pua_map_table[mid].pk < pk_code) lo = mid + 1;")
    lines.append("        else hi = mid - 1;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")
    lines.append("#endif /* PUA_MAP_H */")
    lines.append("")

    header_content = "\n".join(lines)

    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w") as f:
        f.write(header_content)

    print(f"Written {len(table)} entries to {HEADER_PATH}")


if __name__ == "__main__":
    main()
